// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLW0Ftd4wp7NRZHAufqIDfZ_2X0_nAt0Q',
    appId: '1:129176526505:web:7197d67e35431e36b093b8',
    messagingSenderId: '129176526505',
    projectId: 'opinions-app-d7edf',
    authDomain: 'opinions-app-d7edf.firebaseapp.com',
    storageBucket: 'opinions-app-d7edf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsR01OgAL1SYRdZ0uuUc7kC0rTX8C1UfI',
    appId: '1:129176526505:android:ef8c469e83edbcd8b093b8',
    messagingSenderId: '129176526505',
    projectId: 'opinions-app-d7edf',
    storageBucket: 'opinions-app-d7edf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUKKDqMbexXtRP4QSS8lWOoCbEaEI3qIc',
    appId: '1:129176526505:ios:d9ca7576dcd4c421b093b8',
    messagingSenderId: '129176526505',
    projectId: 'opinions-app-d7edf',
    storageBucket: 'opinions-app-d7edf.appspot.com',
    iosClientId: '129176526505-615th8hq87291rp7cforqo1ul151gfqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUKKDqMbexXtRP4QSS8lWOoCbEaEI3qIc',
    appId: '1:129176526505:ios:d9ca7576dcd4c421b093b8',
    messagingSenderId: '129176526505',
    projectId: 'opinions-app-d7edf',
    storageBucket: 'opinions-app-d7edf.appspot.com',
    iosClientId: '129176526505-615th8hq87291rp7cforqo1ul151gfqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppBloc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLW0Ftd4wp7NRZHAufqIDfZ_2X0_nAt0Q',
    appId: '1:129176526505:web:b5eb4b340771cc14b093b8',
    messagingSenderId: '129176526505',
    projectId: 'opinions-app-d7edf',
    authDomain: 'opinions-app-d7edf.firebaseapp.com',
    storageBucket: 'opinions-app-d7edf.appspot.com',
  );
}
